In [1]:
import pandas as pd
import numpy as np

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [12]:
df = pd.read_csv('fraud_data_cleanned.csv')

In [13]:
df.head()

,customer_id,age,gender,country,avg_order_value,total_orders,last_purchase,is_fraudulent,preferred_category,email_open_rate,loyalty_score,churn_risk,customer_tenure_days
0,CUST_1001,64,Male,Germany,112.85,9,73,0,Electronics,50.5,51,0.37,1569
1,CUST_1001,35,Male,UK,252.38,13,224,0,Fashion,86.8,99,0.15,2193
2,CUST_1002,40,Female,Germany,90.38,7,255,1,Beauty,63.4,92,0.10,2215
3,CUST_1004,73,Female,Germany,94.98,9,150,0,Fashion,32.0,49,0.20,2185
4,CUST_1005,43,Male,USA,27.50,10,150,0,Beauty,76.6,13,0.14,1037

In [17]:
data = pd.read_csv('process_data.csv')

In [18]:
data.head(5)

,customer_id,age,gender,country,avg_order_value,total_orders,last_purchase,is_fraudulent,preferred_category,email_open_rate,loyalty_score,churn_risk,customer_tenure_days,total_spend,order_velocity,order_velociy
0,CUST_8270,30,Female,Brazil,101.08,8,176,1,Beauty,25.60,50,0.20,800,808.64,0.156863,0.045198
1,CUST_1860,53,Female,USA,90.39,10,88,0,Electronics,12.30,37,0.34,907,903.90,0.263158,0.112360
2,CUST_6390,73,Male,Australia,83.28,6,203,0,Sports,50.95,65,0.05,850,499.68,0.090909,0.029412
3,CUST_6191,30,Other,Japan,109.90,9,346,1,Electronics,42.90,93,0.19,2228,989.10,0.095745,0.025937
4,CUST_6734,29,Female,Canada,269.38,16,342,0,Fashion,5.30,79,0.15,492,4310.08,0.200000,0.046647

In [30]:
data['country'].unique().tolist()
data['country'].value_counts()

country
Australia    518
USA          517
India        511
Germany      509
Brazil       504
France       500
China        497
Canada       490
UK           485
Japan        469
Name: count, dtype: int64

In [31]:
data['customer_id'].sort_values()
data.to_csv('processed_data', index=False)