# Bismillah 
- Setting up My WorkSpace
- And Importing Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# 1. main eik sath he data sets ko load kar raha hun alag alag
# variable ka use krte hue

customers = pd.read_excel('customers.xlsx')
geography = pd.read_excel('geography.xlsx')
products = pd.read_excel('products.xlsx')
reviews = pd.read_excel('customer_reviews.xlsx')
engagement = pd.read_excel('engagement_data.xlsx')
journey = pd.read_excel('customer_journey.xlsx')

# Step 2: Clean the 'Engagement Data' (Crucial Step!)

In [5]:
# Create a copy to clean
engagement_clean = engagement.copy()

In [21]:
engagement_clean.head(20)

    EngagementID  ContentID  ... ProductID  ViewsClickCombined
0              1         39  ...         9            1883-671
1              2         48  ...        20            5280-532
2              3         16  ...        14            1905-204
3              4         43  ...        20            2766-257
4              5         16  ...        15           5116-1524
5              6         32  ...        19           8237-1641
6              7         33  ...         2              750-34
7              8         47  ...         6              891-35
8              9         48  ...        16           5571-1527
9             10          4  ...        15            4279-297
10            11         38  ...         6            4297-234
11            12         29  ...        10           7877-2037
12            13         14  ...        18            1796-136
13            14          2  ...         2           6837-2251
14            15         16  ...        19                36-1
15            16          2  ...        16           5980-1227
16            17         35  ...        10             563-104
17            18         12  ...         8              321-15
18            19         30  ...         9            1442-400
19            20         35  ...         6                41-7

[20 rows x 8 columns]

In [16]:
engagement_clean['ViewsClickCombined'].value_counts

<bound method IndexOpsMixin.value_counts of 0        1883-671
1        5280-532
2        1905-204
3        2766-257
4       5116-1524
          ...
4618    8115-1872
4619     1273-516
4620     1609-599
4621     3052-374
4622     2458-457
Name: ViewsClickCombined, Length: 4623, dtype: object>

### Remove the two error rows containing date-like entries (e.g., '2000-10-01 00:00:00')

In [20]:
engagement_clean = engagement_clean[~engagement_clean['ViewsClickCombined'].astype(str).str.contains(':')]

### Split the column by the hyphen '~'

In [25]:
split_data = engagement_clean['ViewsClickCombined'].str.split('-', expand=True)
engagement_clean['Views'] = split_data[0].astype(int)
engagement_clean['Clicks'] = split_data[1].astype(int)

/tmp/ipykernel_10153/2016014869.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  engagement_clean['Views'] = split_data[0].astype(int)
/tmp/ipykernel_10153/2016014869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  engagement_clean['Clicks'] = split_data[1].astype(int)

### Now engagement_clean has beautiful, numeric 'Views' and 'Clicks' columns!

In [26]:
print(engagement_clean[['Views', 'Clicks']].head())

   Views  Clicks
0   1883     671
1   5280     532
2   1905     204
3   2766     257
4   5116    1524

In [27]:
engagement_clean.head()

   EngagementID  ContentID ContentType  ...  ViewsClickCombined Views  Clicks
0             1         39        Blog  ...            1883-671  1883     671
1             2         48        Blog  ...            5280-532  5280     532
2             3         16       video  ...            1905-204  1905     204
3             4         43       Video  ...            2766-257  2766     257
4             5         16  newsletter  ...           5116-1524  5116    1524

[5 rows x 10 columns]

# Step 3: Understand How the Files Connect (Data Model)
- Customers & Geography: Connect customers and geography using GeographyID from customers and ID from geography.

- Reviews & Customers/Products: Connect reviews with customers using CustomerID, and with products using ProductID.

- Journey & Customers/Products: Connect journey with customers on CustomerID, and with products on ProductId (note the lowercase 'd'!).

# Let's Do the First Question
- Total kitne unique customers hain?

In [30]:
unique_customers = customers['CustomerID'].nunique()
print(f"Total Unique Customers: {unique_customers}")

Total Unique Customers: 100