In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import (
LogisticRegression,
LinearRegression,
Ridge,
Lasso
)

from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

from sklearn.metrics import (
accuracy_score,
mean_squared_error,
r2_score,
f1_score,
precision_score,
recall_score,
classification_report,
confusion_matrix
)

In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split

from sklearn.linear_model import (LogisticRegression, LinearRegression, Ridge, Lasso)
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import (accuracy_score, mean_squared_error, r2_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix)    

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier, GradientBoostingRegressor

from sklearn.svm import SVC, SVR

from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

# from sklearn.native_bayes import GaussianNB

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [8]:
anagrams = sns.load_dataset('anagrams')

In [10]:
anagrams.head()

   subidr    attnr  num1  num2  num3
0       1  divided     2   4.0     7
1       2  divided     3   4.0     5
2       3  divided     3   5.0     6
3       4  divided     5   7.0     5
4       5  divided     4   5.0     8

In [11]:
anagrams.shape

(20, 5)

In [12]:
anagrams.describe()

         subidr       num1      num2       num3
count  20.00000  20.000000  20.00000  20.000000
mean   10.50000   5.350000   5.97500   6.550000
std     5.91608   1.843195   1.67391   1.099043
min     1.00000   2.000000   3.00000   5.000000
25%     5.75000   4.750000   5.00000   6.000000
50%    10.50000   5.500000   5.50000   6.000000
75%    15.25000   6.250000   7.25000   7.000000
max    20.00000   8.000000   9.00000   9.000000

In [13]:
anagrams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   subidr  20 non-null     int64
 1   attnr   20 non-null     object
 2   num1    20 non-null     int64
 3   num2    20 non-null     float64
 4   num3    20 non-null     int64
dtypes: float64(1), int64(3), object(1)
memory usage: 932.0+ bytes

In [15]:
anagrams.isna().sum()

subidr    0
attnr     0
num1      0
num2      0
num3      0
dtype: int64