# Step 1 : Enviroment Setup and  Data Loading
- phley step zaruri data science aur machine learning libraries
- Pandas
- Scikit-lear
- Matplotlib
- numpy
- seaborn

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings
filterwarnings('ignore')

# usman bhai eik choti si koshish kr raha hun k pipline aur grindsearch ka use krke dekhoun
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import classification_report, mean_absolute_error, mean_squared_error, recall_score, r2_score

In [2]:
# DataSet Load Karain
df = pd.read_csv('housing.csv')

# First 5 rows inspect dekhte hain
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

# Step 2: Exploratory Data Analysis (EDA)
- Dataset ki dimentions, column data types, statistical summary, aur missing values tracd karte hain.

In [3]:
# Dataset shape aur data types
print("DataSet Shape", df.shape)
print("\n--Data Type & Infor--")
df.info()

DataSet Shape (20640, 10)

--Data Type & Infor--
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [4]:
# missing values count
print("\n--Missing Values Per Column--")
print(df.isnull().sum())

--Missing Values Per Column--
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [5]:
# statistical summary
print("\n-- Summary Statistics -- ")
df.describe()

-- Summary Statistics --

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

# Step 3: Feature Engineering
        Raw total features (eg. Total rooms ya total population)
        - rooms_per_household: Average rooms per house.
        - bedrooms_per_room: Propotional of bedrooms relative to                total rooms.
        - population_per_household: Density of occupants per house.

In [12]:
# direct room ratios calculate kar k dekh leta hain
df['rooms_per_household'] = df['total_rooms'] / df['households']
df['bedroom_per_room'] = df['total_bedrooms'] / df["total_rooms"]
df['population_per_household'] = df['population'] / df['households']

# Step : 4 Train-Test Split & Feature Selection
<br>Explanation<br>
<p>Target column median_house_value ko features X se  seprate karain gy. preprocessing ke liye numerical aur categorail columns ko define karne ke baad dataset ko 80% Training aur 20% Testing sets me split karte hain. random_state=42 reproducible results ke liye set karte hain.</p>

In [17]:
# usaman bhai why do i forgot the repeated process like, test, train, split,

In [13]:
#feature (X) aur Target (y) split
X = df.drop('median_house_value', axis=1)
y = df['median_house_value']

In [14]:
# Categorial vs Numerical Feature identification
num_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = ['ocean_proximity']

In [15]:
# Train-Test Split (80# Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

In [16]:
print(f"X_train shape: {X_train.shape} | X_test shape: {X_test.shape}")

X_train shape: (16512, 12) | X_test shape: (4128, 12)

# Step 5: Data Preprocessing Pipeline Construction
Explation:
Data leake avoid karne aur modular trasformaiton k liye Scikit_learn pipelines use karta hai.

1: numercial Pipeline: SimpleImputer (media strategy) se missing values fill karte hain aur (standardScaler) se numerical features ko standard normal distribution (mean=0, std=1) me bring krte hain.

2: Categorcal Pipeline: Categorical variable occean_prximity ko OneHotEncoder(drop='first') se encode krte hain taake dummy variable trap se bacha ja sake

3: ColumnTransformer: Dono pipelines ko single interface me join krta ha.

In [18]:
# PipeLine for Numerical Features
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [19]:
# Pipeline for categorical Features
cat_pipeline = Pipeline([
    ('encoer', OneHotEncoder(drop='first', handle_unknown='ignore'))
])

In [20]:
# Master ColumnTransformer
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

# Step 6: Model Training & Comparative Evaluation
Explaination
- Multiple Regression algorithms(LinearRegression, DecisionTreeRegressor, RandomForestRegressor, GredientBostingRegressor)
- metrices(MAE, MSE, RMSE, R2 Score) par evaluate aur compare krte hain

In [30]:
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42, n_jobs=-1),
    'Gradient Boosting': GradientBoostingRegressor(random_state=42)
}

results = []

for name, model in models.items():
    # Model Pipeline combine karein
    full_pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('model', model)
    ])
    
    # Train
    full_pipeline.fit(X_train, y_train)
    
    # Predict on Test Set
    y_pred = full_pipeline.predict(X_test)
    
    # Calculate Metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)
    
    results.append({
        'Model': name,
        'MAE': round(mae, 2),
        'MSE': round(mse, 2),
        'RMSE': round(rmse, 2),
        'R2 Score': round(r2, 4)
    })

# Metrics comparison table
comparison_df = pd.DataFrame(results).sort_values(by='R2 Score', ascending=False)
comparison_df

               Model       MAE           MSE      RMSE  R2 Score
2      Random Forest  31933.03  2.481544e+09  49815.09    0.8106
3  Gradient Boosting  36523.02  2.874260e+09  53612.12    0.7807
0  Linear Regression  49645.49  4.778547e+09  69127.04    0.6353
1      Decision Tree  43329.01  4.955856e+09  70397.84    0.6218

# Step 7: Hyperparameter Tuning
(Best Model Optimization)Explanation:Random Forest Regression sab se superior R2 score ($> 0.81$) offer karta hai. 
Is broad performance ko further refine karne ke liye GridSearchCV se hyperparameter optimization apply karte hain.

In [31]:
# Tuning pipeline setup
tuning_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(random_state=42, n_jobs=-1))
])

# Search grid define karein
param_grid = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [20, None],
    'model__max_features': ['sqrt', 1.0]
}

grid_search = GridSearchCV(
    estimator=tuning_pipeline,
    param_grid=param_grid,
    cv=3,
    scoring='r2',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best CV R2 Score:", round(grid_search.best_score_, 4))

Best Parameters: {'model__max_depth': None, 'model__max_features': 'sqrt', 'model__n_estimators': 200}
Best CV R2 Score: 0.8108